### ISSUE TITLE
Fluent-smtp doesn't comply with Google's OAuth 2.0 policy

### ISSUE THREAD

**Issue by larsnvg** [WPManageNinja/fluent-smtp#100] opened 2022-05-24 19:03 UTC
I can't connect my google mail with Fluent SMTP.  get an 400 Error like below 
<img width="546" alt="Screenshot 2022-05-24 at 20 54 41" src="https://user-images.githubusercontent.com/106186322/170112604-f6389896-3787-4fdd-bbb4-414f51cf0eba.png">
:
Authorization Error
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob

**Comment by jvandijk** [comment] 2022-06-05 20:37
This is a duplicate of this issue : https://github.com/WPManageNinja/fluent-smtp/issues/88

**Comment by techjewel** [comment] 2022-07-05 09:07
Issue has been fixed in the latest version.

**Closed by techjewel** 2022-07-05 09:07 UTC
